import { StyleSheet } from "react-native";
import { tokens } from "../../theme";

export const blockStyles = StyleSheet.create({
  row: { flexDirection: "row" },
  rowEnd: { justifyContent: "flex-end" },
  rowStart: { justifyContent: "flex-start" },
  bubble: {
    maxWidth: "85%",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  fullWidthBubble: { maxWidth: "100%" },
  userBubble: {
    backgroundColor: tokens.colors.interactiveAccent,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 4,
    borderBottomLeftRadius: 16,
  },
  agentBubble: {
    backgroundColor: tokens.colors.interactiveAccent,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 4,
  },
  thinkingBubble: {
    maxWidth: "85%",
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: "rgba(90, 62, 141, 0.95)",
    opacity: 0.78,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 4,
  },
  thinkingToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  thinkingLabel: {
    color: tokens.colors.textOnAccent,
    fontSize: 9.5,
    fontWeight: "600",
    letterSpacing: 0.5,
    opacity: 0.8,
  },
  thinkingPreview: {
    color: tokens.colors.textOnAccent,
    fontStyle: "italic",
    fontSize: 11.5,
    lineHeight: 16,
  },
  thinkingContentScroll: {
    maxHeight: 72,
  },
  chevron: { color: tokens.colors.textMuted, fontSize: tokens.fontSizes.caption2 },
  streamingCursor: { color: tokens.colors.textOnAccent },
  cursor: {
    width: 6,
    height: 14,
    backgroundColor: tokens.colors.textOnAccent,
    borderRadius: 3,
    marginTop: 4,
    opacity: 0.9,
  },
  cursorDark: {
    width: 6,
    height: 12,
    backgroundColor: tokens.colors.textMuted,
    borderRadius: 3,
    opacity: 0.7,
  },
  toolCard: {
    alignSelf: "flex-start",
    maxWidth: "90%",
    borderWidth: 1,
    borderColor: tokens.colors.modifierBorder,
    borderRadius: 8,
    overflow: "hidden",
  },
  toolCardPressed: { opacity: 0.94 },
  toolHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: tokens.colors.modifierHover,
  },
  toolLabel: {
    fontSize: 10,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: tokens.colors.textMuted,
  },
  toolName: {
    fontFamily: tokens.fonts.mono,
    fontWeight: "600",
    color: tokens.colors.textNormal,
    flex: 1,
    fontSize: 12,
  },
  toolStatus: {
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    borderRadius: 999,
    color: tokens.colors.textMuted,
    fontSize: 10,
    fontWeight: "600",
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  toolStatusRunning: { color: "#f8d477" },
  toolStatusDone: { color: "#9ff0b4" },
  toolStatusError: { color: tokens.colors.textError },
  toolBody: { borderTopWidth: 1, borderTopColor: tokens.colors.modifierBorder },
  toolCall: { backgroundColor: tokens.colors.backgroundSecondary },
  toolScroll: { maxHeight: 72 },
  toolArgs: {
    margin: 0,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontFamily: tokens.fonts.mono,
    fontSize: 11.5,
    color: tokens.colors.textNormal,
  },
  toolResult: {
    backgroundColor: tokens.colors.backgroundPrimary,
    borderTopWidth: 1,
    borderTopColor: tokens.colors.modifierBorder,
  },
  toolResultError: {},
  toolResultLabel: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 10,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: tokens.colors.textMuted,
    backgroundColor: tokens.colors.modifierHover,
  },
  toolResultLabelError: { color: tokens.colors.textError },
  toolResultContent: {
    margin: 0,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontFamily: tokens.fonts.mono,
    fontSize: 11.5,
    color: tokens.colors.textNormal,
  },
  toolResultContentError: { color: tokens.colors.textError },
  errorCard: {
    borderWidth: 1,
    borderColor: tokens.colors.dangerBorder,
    backgroundColor: tokens.colors.dangerBg,
    borderRadius: tokens.radii.md,
    padding: tokens.spacing.md,
    gap: tokens.spacing.xxs,
    maxWidth: "85%",
  },
  errorLabel: {
    color: tokens.colors.textError,
    fontWeight: "700",
    fontSize: tokens.fontSizes.caption,
    letterSpacing: 0.5,
  },
  errorText: { color: tokens.colors.textNormal, fontSize: tokens.fontSizes.bodySm },
});
