import path from "node:path";
import { readFile } from "node:fs/promises";
import { pathExists } from "./workspaceFs.js";

export const DEFAULT_EMPTY_INSTRUCTIONS = "No user-authored instructions have been added for this environment yet. You may edit this file upon the user's request to save simple instructions or reminders. Complex instructions and processes belong in the skill files for this environment.";

export type AggregateSource = { nickname: string; sourcePath: string; displayPath: string; writable: boolean };
export type AggregateFact = { nickname: string; environmentName: string; bundleName: string; name: string; content: string };

export async function renderAggregateAgents(
  root: string,
  sources: AggregateSource[],
  inlineFacts: AggregateFact[],
  skillNamesByEnvironment: Map<string, Set<string>>,
  skillAuthoringPaths: Map<string, string>,
): Promise<string> {
  const blocks = (await Promise.all(sources.map(async (source) => {
    const absoluteSource = path.isAbsolute(source.sourcePath) ? source.sourcePath : path.join(root, source.sourcePath);
    if (!(await pathExists(absoluteSource))) return undefined;
    const content = await readFile(absoluteSource, "utf8");
    const editable = source.writable ? "true" : "false";
    const pathAttribute = source.writable ? ` path="${escapeAttribute(source.displayPath)}"` : "";
    return `<environment_instruction environment="${escapeAttribute(source.nickname)}" editable="${editable}"${pathAttribute}>\n${content.trim()}\n</environment_instruction>`;
  }))).filter((block): block is string => block !== undefined);
  const factBlocks = inlineFacts.map((fact) => `<environment_instruction environment="${escapeAttribute(fact.nickname)}" editable="false">\n${fact.name}: ${fact.content.trim()}\n</environment_instruction>`);
  const environmentNames = [...new Set([
    ...sources.map((source) => source.nickname),
    ...skillNamesByEnvironment.keys(),
  ])].sort((a, b) => a.localeCompare(b));
  const locations = [...skillAuthoringPaths.entries()].sort(([a], [b]) => a.localeCompare(b));
  const locationText = locations.length > 0
    ? locations.map(([nickname, authoringPath]) => `- For the \`${nickname}\` environment, add, edit, or delete skills in \`${authoringPath}/<skill-name>/SKILL.md\`.`).join("\n")
    : "No environments are currently entered with writable projected skill authoring locations.";
  const exampleNickname = locations.some(([nickname]) => nickname === "example-com") ? "example-com" : locations[0]?.[0];
  const examplePath = exampleNickname ? skillAuthoringPaths.get(exampleNickname) : undefined;
  const example = exampleNickname && examplePath ? `\nUse the normal Agent Skills format. For example, to create a very simple skill in the visible projected path for ${exampleNickname}:\n\n\`\`\`sh\nmkdir -p ${examplePath}/say-hello\ncat > ${examplePath}/say-hello/SKILL.md <<'EOF'\n---\nname: say-hello\ndescription: Say hello when the user asks for a greeting.\n---\n\nWhen asked for a greeting, say hello.\nEOF\n\`\`\`\n\nOnce \`SKILL.md\` exists, Rook will preserve it and refresh the projected \`.agents/skills/\` inventory automatically.` : "";
  const skillInventory = environmentNames.map((nickname) => {
    const names = [...(skillNamesByEnvironment.get(nickname) ?? [])].sort((a, b) => a.localeCompare(b));
    return `- \`${nickname}\`: ${names.length > 0 ? names.map((name) => `\`${formatInlineCode(name)}\``).join(", ") : "none"}`;
  }).join("\n");
  return `# Rook environment instructions

This file is generated by Rook and is read-only. Do not edit it directly.

Treat the visible projected paths in this workspace as authoritative. When you need to add, edit, or delete instructions, memories, skills, or processes, do it through those visible paths rather than resolving symlinks or searching for backing stores. After edits, deletions, or creations, the projected files and this aggregate may refresh shortly afterward; trust that automatic rematerialization.

## Adding, editing, and deleting instructions and memories

Instructions and memories are usually small pieces of guidance, facts, or reminders associated with an environment that the agent should keep in mind while working there.

Each environment's instructions and memories appear inside the \`<environment_instruction>\` tags below. Use the instruction text as context.

The tag attributes mean:

- \`environment\` is the path-safe environment nickname.
- \`editable=\"false\"\` marks instructions that come from a read-only source.
- \`editable=\"true\"\` marks instructions that the user may edit.
- \`path\` identifies the visible projected file to edit for writable instructions. Paths are relative.

When an editable block has a \`path\`, edit that visible path rather than this generated aggregate. Do not resolve symlinks or hunt for deeper backing stores. If an editable block contains only the default message, no user-authored instructions or memories exist for that environment yet.

## Adding, editing, and deleting skills and processes

Skills usually hold deeper or more reusable procedures that can be applied when working in an environment.

Skills are discovered from \`.agents/skills/\`, but treat that directory as inventory only. Do not add, edit, or delete skills there, even if some entries appear writable.

Instead, for writable environments, add, edit, or delete skills only through the visible projected environment skill directories listed below. Do not resolve symlinks, search for deeper backing stores, or try to force read-only skill directories writable by changing permissions, replacing links, or copying files elsewhere.

Do not create new skills directly under \`.agents/skills/\`. For writable environments, use the visible projected environment skill directories:

${locationText}${example}

## Environment instructions and memories

${[...blocks, ...factBlocks].join("\n\n")}

## Environment skills and procedures

The following list shows the skills currently known for each environment.

${skillInventory || "- none"}
`;
}

export function writableInstructionsContent(content: string | undefined): string {
  return content?.trim() ? content : DEFAULT_EMPTY_INSTRUCTIONS;
}

function escapeAttribute(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("\"", "&quot;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
}

function formatInlineCode(value: string): string {
  return value.replaceAll("`", "\\`");
}
